### ISSUE TITLE
Transition is not working with a Timer

### ISSUE THREAD

**Issue by fluffy919** [indieSoftware/NavigationStack#2]
I used Timer for auto transition after 3 seconds, but it caused a fatal error.
<img width="506" alt="Screen Shot 2021-06-09 at 10 41 08 PM" src="https://user-images.githubusercontent.com/28706536/121456310-deb8b100-c973-11eb-8ecf-201d7534c8e1.png">

<img width="782" alt="Screen Shot 2021-06-09 at 10 39 53 PM" src="https://user-images.githubusercontent.com/28706536/121456190-ac0eb880-c973-11eb-88ca-182a827d4436.png">
")

**Comment by indieSoftware** [comment]
This error is thrown when trying to replace a current detail view with another detail view without first navigating back. Let's say you have an overview A and you are navigating to a detail view B and from detail view B you now try to replace view B with view C by telling view A to navigate to view C while it still shows view B. That doesn't work and leads to that exception. I guess you want to navigate from view B to view C therefore you should tell view B rather than view A to show view C. That would then lead to a view hierarchy A-B-C. If you really want to end with a view hierarchy like A-C then you have first to tell view A to dismiss view B before telling it to show view C.

**Comment by fluffy919** [comment]
Thanks for your explanation. Can you share some example code?

**Comment by fluffy919** [comment]
What if I need a navigation bar? Is there any trouble combining NavigationStack and default NavigationView?

**Comment by indieSoftware** [comment]
There is an example project in the lib's sources you can look at when checking out the repo. Just look at the `ContentViewX` files in https://github.com/indieSoftware/NavigationStack/tree/master/Sources/NavigationStackExample/ExampleViews.

In essence when you want to show a View B from View A then you have to add the following call in the body / scope of View A:
```
navigationModel.showView("View A") { ViewB() }
```

And when you want go back from View B to View A you need to have a call like the following in View B:
```
navigationModel.hideView("View A")
```

Therefore, when you now want to go from View B to View C you need appropriately a call in View B as the following:
```
navigationModel.showView("View B") { ViewC() }
```

When you reference to "View A" instead of "View B" inside of ViewB then you will receive the error you are receiving. Therefore, all you have to do is change that reference, because when you are navigating from View B to View C you want to change the content of the View B's navigation view, not that one from View A because that has already its content swapped to show View B.

**Comment by indieSoftware** [comment]
Regarding your second question about the NavigationView, the NavigationStack library is not designed to work together with NavigationView. You can of course embed a NavigationView inside of a view which is then presented by the NavigationStack or vice versa and it should work for each navigation type, but you can't use a NavigationLink for triggering the NavigationStack transition and when mixing the navigation methods you will certainly end up with bugs and problems. I wouldn't recommend mixing two different navigation approaches.

**Comment by fluffy919** [comment]
Thanks for your reply. I already have a look at the example ContentViews. I am sure that my case is different from what you are saying.
My flow is something like this.
Showing "ViewB" from "ViewA" is okay, but showing "ViewC" from "ViewB" is not working. I used timer for transition from B to C.
There is no mistake about the references.
<img width="480" alt="Screen Shot 2021-06-11 at 9 34 10 AM" src="https://user-images.githubusercontent.com/28706536/121694624-4700b300-ca98-11eb-876a-7284f02c27bc.png">

**Comment by fluffy919** [comment]
FYI, I tried the same transition with Button action, it went well. Is there any issue with Timer in NavigationStack?

**Comment by fluffy919** [comment]
I have another question.
There are 2 transitions.
From ViewA to ViewC
From ViewB to ViewC

In this case, Cancel/Close button with hideView() crashes. How to solve this?

**Comment by indieSoftware** [comment]
It's hard to say what's going wrong in your code without really seeing your whole code. If you can create a reduced example project of your code with only what's really necessary to show-case the problem (maybe with some code comments what you are trying to do, what you are expecting, what is not working, etc) and upload that example project to a repository in your account then I will look at it and give you feedback.

**Comment by fluffy919** [comment]
Have you ever tried auto showView with Timer? Does it work before? If so, please share the sample of that. Thanks

**Comment by indieSoftware** [comment]
I have created a small experiment number 11 to show-case that it works with a timer. However, it depends how you implement this, but that's up to you. You can check the experiment out on the timedTransition branch: https://github.com/indieSoftware/NavigationStack/tree/timedTransition
Just run the NavigationStackExample scheme with the Experiment11 activated as argument.
